# Generated by Django 4.2.16 on 2024-09-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iupac_name', models.CharField(max_length=255)),
                ('molecular_formula', models.CharField(max_length=255)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('cid', models.IntegerField(unique=True)),
                ('bonds', models.CharField(max_length=200)),
                ('synonyms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=8)),
                ('mass', models.IntegerField()),
                ('group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreeCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='chemappapi.compound')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemappapi.tree')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree', to='chemappapi.user'),
        ),
        migrations.CreateModel(
            name='CompoundElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemappapi.compound')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemappapi.element')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='elements',
            field=models.ManyToManyField(related_name='compounds', through='chemappapi.CompoundElement', to='chemappapi.element'),
        ),
        migrations.AddField(
            model_name='compound',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='chemappapi.user'),
        ),
    ]
