# Generated by Django 4.2.16 on 2024-09-14 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemappapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='info_link',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
