# Generated by Django 4.1.3 on 2024-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemappapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='mass',
            field=models.IntegerField(),
        ),
    ]
